services:
  backend:
    image: python-backend:1.0.0
    ports:
      - 8001:8001
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
  
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    image: es6-frontend:1.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app  # Gắn thư mục hiện tại vào container
      - /usr/src/app/node_modules  # Tránh xóa các node_modules cục bộ
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
    depends_on:
      - backend

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt