name: Pipeline React Frontend Project
on:
  push:
   branches: master
   with:
      - Docker/Frontend/**
      - 'docker-compose.yaml'
      - Frontend/learn-jointjs-react-main/**
      - .github/workflows/*-frontend.yaml

jobs:
  build: 
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Login To DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v3
      
      - name: Build & Push Docker
        uses: docker/build-push-action@v6
        with:
         context: Frontend/learn-jointjs-react-main
         file: ../../Docker/Frontend/Dockerfile
         platforms: linux/amd64
         tags: |
            ${{secrets.DOCKER_USERNAME}}/react-ui:latest
            ${{secrets.DOCKER_USERNAME}}/react-ui:1.0.0
          
        


    
