name: Pipeline Python Backend Project

on:
  push:
    branches:
      - master
    with:
      - Docker/Backend/**
      - 'docker-compose.yaml'
      - Backend/python_backend_demo/**
      - .github/workflows/*-backend.yaml

jobs:
  build-project-and-push-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/python_backend_demo/requirements.txt
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Docker/Backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/python-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/python-backend:1.0.0  
